name = "lumina_client"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_json = "2.3.0"
gleam_stdlib = "0.59.0"
lustre = ">= 5.0.3 and < 6.0.0"
lustre_websocket = ">= 0.9.0 and < 1.0.0"
gleamy_lights = ">= 2.3.0 and < 3.0.0"
plinth = ">= 0.5.9 and < 1.0.0"
gleam_time = ">= 1.4.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
