[local-devel]
description = "Run the server in development mode"
depends = "build-server"
run = ["../target/debug/lumina-server"]
run_windows = "..\\target\\debug\\lumina-server.exe"
dir = "{{config_root}}/data/"
env.LUMINA_POSTGRES_PASSWORD = "lumina_pw"

[local-devel-watch]
tools.watchexec = "latest"
description = "Run the server in development mode with file watching"
run = "watchexec --restart --stop-timeout=0 --shell=sh -e rs,gleam,toml,css,ts,json mise run local-devel"
run_windows = "watchexec --restart --stop-timeout=0 --shell=cmd -e rs,gleam,toml,css,ts,json mise run local-devel"
env.LUMINA_POSTGRES_PASSWORD = "lumina_pw"
